### ISSUE TITLE
Is possible to add Cookies parse?

### ISSUE THREAD

**Issue by mastercho** [Frizz925/php-curl-parser#2]
I notice is parse all headers but not Cookies, probably because doesn't have -H as i saw in code.

Do you mind to add it?

Also, i notice is fails to parse `multipart/form-data; boundary=----WebKitFormBoundaryjQKVSuoFOtbPwdfs` Content type  data :( Need fix!

**Comment by frizz925** [comment]
It's ignored by default as cookies should be stored in different manner compared to other headers.
https://github.com/Frizz925/php-curl-parser/blob/bc077b7ccd5c3c160a38abf7167eea4be3bd9d86/src/Parser.php#L40-L42

I may introduce cookies parsing that complies with [PSR-7 ServerRequestInterface](https://github.com/php-fig/http-message/blob/master/src/ServerRequestInterface.php) in the next minor version bump (1.1.0). If anyone has different idea on how the cookies header should parsed, I'm open for suggestion.

As for parsing with `multipart/form-data` body, I'll release a new patch sometime this week.

**Comment by frizz925** [comment]
@mastercho Can you give an example of cURL request that you used for `multipart/form-data`? Mine seems to pass the tests just fine.

**Comment by mastercho** [comment]
`curl 'https://utcoinbets.com/index.php?route=account/login' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Origin: https://utcoinbets.com' -H 'Upgrade-Insecure-Requests: 1' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryG7ap9KXBofCbaecM' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'Referer: https://utcoinbets.com/index.php?route=account/login' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: bg,en-US;q=0.9,en;q=0.8,tr;q=0.7' -H 'Cookie: language=en; currency=EUR; PHPSESSID=spkdti92stljah82s3s20ltpa7' --data-binary $'------WebKitFormBoundaryG7ap9KXBofCbaecM\r\nContent-Disposition: form-data; name="email"\r\n\r\ntesting2@gmail.com\r\n------WebKitFormBoundaryG7ap9KXBofCbaecM\r\nContent-Disposition: form-data; name="password"\r\n\r\nTeestin2\r\n------WebKitFormBoundaryG7ap9KXBofCbaecM--\r\n' --compressed`

Here in bash format. I'm using your library to convert from bash to my json template. So yea when i try this data-binary is not parsed fully (probably because is in new line)

**Comment by frizz925** [comment]
`--data-binary $'`

This seems to be the culprit. The parser can't handle bash (or anything in particular) string manipulation. This would also mean newlines written using literal `\r\n` would also be parsed literally (instead of being converted into proper newlines). You can check for a working example of `multipart/form-data` parsing from [the following fixture](https://github.com/Frizz925/php-curl-parser/blob/master/fixtures/CharlesImageUpload.txt).

**Comment by mastercho** [comment]
Got it so if i copy like cmd format from Chrome Dev tools not like bash would work (only if i first escape ^ from it.) Thanks for clarifying this. I'll wait cookies parse update.

**Comment by frizz925** [comment]
Yeah it's meant to parse cURL request from tools like Charles Web Proxy or Chrome DevTools.

**Comment by frizz925** [comment]
Man this takes quite a long time. Cookies parsing implemented in https://github.com/Frizz925/php-curl-parser/commit/338607a83df695e82f3017ea387129999e5eca3a and would be included by the next minor release 😀
